defmodule MonoPhoenixV01Web.CoreComponents do
  @moduledoc """
  Core UI components for auth pages generated by phx.gen.auth.
  Bridges the Phoenix 1.7+ component system with this pre-1.7 app.
  """
  use Phoenix.Component

  alias Phoenix.LiveView.JS

  @doc "Renders a page header with optional subtitle slot."
  slot :inner_block, required: true
  slot :subtitle

  def header(assigns) do
    ~H"""
    <div class="mb-4">
      <h1 class="text-2xl">{render_slot(@inner_block)}</h1>
      <p :if={@subtitle != []} class="mt-1 text-sm text-gray-600">
        {render_slot(@subtitle)}
      </p>
    </div>
    """
  end

  @doc "Renders a button."
  attr :variant, :string, default: nil
  attr :class, :string, default: nil
  attr :rest, :global, include: ~w(disabled phx-disable-with name value)
  slot :inner_block, required: true

  def button(assigns) do
    variant_class =
      case assigns[:variant] do
        "primary" -> "btn btn-primary"
        "soft" -> "btn btn-soft"
        _ -> nil
      end

    assigns = assign(assigns, :variant_class, variant_class)

    ~H"""
    <button class={[@variant_class, @class]} {@rest}>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "Renders an input with label and error messages. Accepts a form field or explicit attrs."
  attr :id, :any, default: nil
  attr :name, :any, default: nil
  attr :label, :string, default: nil
  attr :value, :any, default: nil
  attr :type, :string, default: "text"
  attr :field, :any, default: nil
  attr :errors, :list, default: []
  attr :checked, :boolean, default: false
  attr :prompt, :string, default: nil
  attr :options, :list, default: []
  attr :multiple, :boolean, default: false
  attr :rest, :global,
    include: ~w(accept autocomplete capture cols disabled form list max maxlength min
                multiple pattern placeholder readonly required rows size step phx-mounted phx-debounce)

  def input(%{field: field} = assigns) when not is_nil(field) do
    errors =
      Enum.map(field.errors, fn {msg, opts} ->
        Regex.replace(~r"%{(\w+)}", msg, fn _, key ->
          opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
        end)
      end)

    assigns
    |> assign(
      field: nil,
      id: assigns.id || field.id,
      name: (if assigns.multiple, do: field.name <> "[]", else: field.name),
      value: field.value,
      errors: errors
    )
    |> input()
  end

  def input(%{type: "select"} = assigns) do
    ~H"""
    <div>
      <label :if={@label} for={@id} class="block text-sm font-medium">{@label}</label>
      <select id={@id} name={@name} multiple={@multiple} class="mt-1 block w-full" {@rest}>
        <option :if={@prompt} value="">{@prompt}</option>
        {Phoenix.HTML.Form.options_for_select(@options, @value)}
      </select>
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  def input(%{type: "checkbox"} = assigns) do
    assigns = assign_new(assigns, :checked, fn ->
      Phoenix.HTML.Form.normalize_value("checkbox", assigns[:value])
    end)

    ~H"""
    <div>
      <label class="flex items-center gap-2 text-sm font-medium">
        <input type="hidden" name={@name} value="false" />
        <input type="checkbox" id={@id} name={@name} value="true" checked={@checked} {@rest} />
        {@label}
      </label>
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  def input(%{type: "password"} = assigns) do
    ~H"""
    <div>
      <label :if={@label} for={@id} class="block text-sm font-medium">{@label}</label>
      <div
        id={"password-toggle-#{@id}"}
        phx-hook="PasswordToggle"
        class="password-toggle-wrapper"
        style="position: relative;"
      >
        <input
          type={@type}
          name={@name}
          id={@id}
          value={Phoenix.HTML.Form.normalize_value(@type, @value)}
          class="mt-1 block w-full border border-gray-300 rounded"
          style="padding-right: 42px;"
          {@rest}
        />
        <button
          type="button"
          title="Show password"
          aria-label="Show password"
          class="password-toggle-btn"
          tabindex="-1"
          style="position: absolute; right: 8px; top: 50%; transform: translateY(-50%); background: transparent; border: none; cursor: pointer; padding: 6px; line-height: 0; color: #5E2612; display: inline-flex; align-items: center; justify-content: center;"
        >
          <span class="eye-open" style="display: inline-flex; align-items: center;">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" /><circle cx="12" cy="12" r="3" /></svg>
          </span>
          <span class="eye-shut" style="display: none; align-items: center;">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24" /><line x1="1" y1="1" x2="23" y2="23" /></svg>
          </span>
        </button>
      </div>
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  def input(assigns) do
    ~H"""
    <div>
      <label :if={@label} for={@id} class="block text-sm font-medium">{@label}</label>
      <input
        type={@type}
        name={@name}
        id={@id}
        value={Phoenix.HTML.Form.normalize_value(@type, @value)}
        class="mt-1 block w-full border border-gray-300 rounded"
        {@rest}
      />
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  @doc "Renders an icon span (uses hero-* class names)."
  attr :name, :string, required: true
  attr :class, :string, default: nil

  def icon(assigns) do
    ~H"""
    <span class={["icon", @name, @class]} aria-hidden="true"></span>
    """
  end

  @doc "Renders a flash notice."
  attr :flash, :map, default: %{}
  attr :kind, :atom, values: [:info, :error]
  attr :id, :string, doc: "optional id"
  attr :rest, :global

  slot :inner_block

  def flash(assigns) do
    assigns = assign_new(assigns, :id, fn -> "flash-#{assigns.kind}" end)

    ~H"""
    <div
      :if={msg = render_slot(@inner_block) || Phoenix.Flash.get(@flash, @kind)}
      id={@id}
      role="alert"
      class={["flash-notice", @kind == :info && "flash-info", @kind == :error && "flash-error"]}
      {@rest}
    >
      {msg}
    </div>
    """
  end

  @doc "Shows the flash group."
  attr :flash, :map, required: true
  attr :id, :string, default: "flash-group"

  def flash_group(assigns) do
    ~H"""
    <div id={@id}>
      <.flash kind={:info} flash={@flash} />
      <.flash kind={:error} flash={@flash} />
    </div>
    """
  end
end
