defmodule MonoPhoenixV01Web.CoreComponents do
  @moduledoc """
  Core UI components for auth pages generated by phx.gen.auth.
  Bridges the Phoenix 1.7+ component system with this pre-1.7 app.
  """
  use Phoenix.Component

  alias Phoenix.LiveView.JS

  @doc "Renders a page header with optional subtitle slot."
  slot :inner_block, required: true
  slot :subtitle

  def header(assigns) do
    ~H"""
    <div class="mb-4">
      <h1 class="text-2xl font-semibold">{render_slot(@inner_block)}</h1>
      <p :if={@subtitle != []} class="mt-1 text-sm text-gray-600">
        {render_slot(@subtitle)}
      </p>
    </div>
    """
  end

  @doc "Renders a button."
  attr :variant, :string, default: nil
  attr :class, :string, default: nil
  attr :rest, :global, include: ~w(disabled phx-disable-with name value)
  slot :inner_block, required: true

  def button(assigns) do
    ~H"""
    <button class={[@class]} {@rest}>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "Renders an input with label and error messages."
  attr :id, :any, default: nil
  attr :name, :any, default: nil
  attr :label, :string, default: nil
  attr :value, :any, default: nil
  attr :type, :string, default: "text"
  attr :errors, :list, default: []
  attr :checked, :boolean, doc: "the checked flag for checkbox inputs"
  attr :prompt, :string, default: nil
  attr :options, :list, doc: "the options to pass to Phoenix.HTML.Form.options_for_select/2"
  attr :multiple, :boolean, default: false
  attr :field, Phoenix.HTML.FormField, doc: "a form field struct"
  attr :rest, :global, include: ~w(accept autocomplete capture cols disabled form list max maxlength min minmax multiple pattern placeholder readonly required rows size step phx-mounted phx-debounce)

  def input(%{field: %Phoenix.HTML.FormField{} = field} = assigns) do
    errors =
      Enum.map(field.errors, fn {msg, opts} ->
        Regex.replace(~r"%{(\w+)}", msg, fn _, key ->
          opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
        end)
      end)

    assigns
    |> assign(field: nil, id: assigns.id || field.id)
    |> assign(:errors, errors)
    |> assign_new(:name, fn -> if assigns.multiple, do: field.name <> "[]", else: field.name end)
    |> assign_new(:value, fn -> field.value end)
    |> input()
  end

  def input(%{type: "select"} = assigns) do
    ~H"""
    <div>
      <label :if={@label} for={@id} class="block text-sm font-medium">{@label}</label>
      <select id={@id} name={@name} multiple={@multiple} class="mt-1 block w-full" {@rest}>
        <option :if={@prompt} value="">{@prompt}</option>
        {Phoenix.HTML.Form.options_for_select(@options, @value)}
      </select>
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  def input(%{type: "checkbox"} = assigns) do
    assigns =
      assign_new(assigns, :checked, fn ->
        Phoenix.HTML.Form.normalize_value("checkbox", assigns[:value])
      end)

    ~H"""
    <div>
      <label class="flex items-center gap-2 text-sm font-medium">
        <input type="hidden" name={@name} value="false" />
        <input type="checkbox" id={@id} name={@name} value="true" checked={@checked} {@rest} />
        {@label}
      </label>
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  def input(assigns) do
    ~H"""
    <div>
      <label :if={@label} for={@id} class="block text-sm font-medium">{@label}</label>
      <input
        type={@type}
        name={@name}
        id={@id}
        value={Phoenix.HTML.Form.normalize_value(@type, @value)}
        class="mt-1 block w-full border border-gray-300 rounded"
        {@rest}
      />
      <p :for={error <- @errors} class="mt-1 text-sm text-red-600">{error}</p>
    </div>
    """
  end

  @doc "Renders an icon span (uses hero-* class names)."
  attr :name, :string, required: true
  attr :class, :string, default: nil

  def icon(assigns) do
    ~H"""
    <span class={["icon", @name, @class]} aria-hidden="true"></span>
    """
  end

  @doc "Renders a flash notice."
  attr :flash, :map, default: %{}
  attr :kind, :atom, values: [:info, :error]
  attr :id, :string, doc: "optional id"
  attr :rest, :global

  slot :inner_block

  def flash(assigns) do
    assigns = assign_new(assigns, :id, fn -> "flash-#{assigns.kind}" end)

    ~H"""
    <div
      :if={msg = render_slot(@inner_block) || Phoenix.Flash.get(@flash, @kind)}
      id={@id}
      role="alert"
      class={["flash-notice", @kind == :info && "flash-info", @kind == :error && "flash-error"]}
      {@rest}
    >
      {msg}
    </div>
    """
  end

  @doc "Shows the flash group."
  attr :flash, :map, required: true
  attr :id, :string, default: "flash-group"

  def flash_group(assigns) do
    ~H"""
    <div id={@id}>
      <.flash kind={:info} flash={@flash} />
      <.flash kind={:error} flash={@flash} />
    </div>
    """
  end
end
