defmodule MonoPhoenixV01Web.Layouts do
  @moduledoc """
  Provides layout components for auth pages generated by phx.gen.auth.
  The `app` component wraps content in a minimal page shell compatible
  with this pre-1.7 Phoenix app.
  """
  use Phoenix.Component

  import MonoPhoenixV01Web.CoreComponents

  @doc """
  Renders the app layout shell.
  Used by phx.gen.auth LiveViews (login, registration, settings, etc.).
  """
  attr :flash, :map, required: true
  attr :current_scope, :any, default: nil
  slot :inner_block, required: true

  def app(assigns) do
    ~H"""
    <div class="auth-page-wrapper">
      <.flash_group flash={@flash} />
      <main class="auth-main">
        {render_slot(@inner_block)}
      </main>
    </div>
    """
  end
end
