defmodule MonoPhoenixV01Web.Layouts do
  @moduledoc """
  Provides layout components for auth pages generated by phx.gen.auth.
  The `app` component wraps content in a minimal page shell compatible
  with this pre-1.7 Phoenix app.
  """
  use Phoenix.Component

  import MonoPhoenixV01Web.CoreComponents

  @doc """
  Renders the app layout shell.
  Used by phx.gen.auth LiveViews (login, registration, settings, etc.).
  """
  attr :flash, :map, required: true
  attr :current_scope, :any, default: nil
  attr :page_class, :string, default: nil
  slot :inner_block, required: true

  # The live.html.heex layout already renders flash messages globally at the
  # top of every LiveView page, so we don't render <.flash_group> here (doing
  # so would show the same message twice).
  def app(assigns) do
    ~H"""
    <div class={["auth-page-wrapper", @page_class]}>
      <main class="auth-main">
        {render_slot(@inner_block)}
      </main>
    </div>
    """
  end
end
